
"Ad.com":
    action: ""
    params: 
      username: ""
      password: ""


"AdBrite":
    action: ""
    params: 
      username: ""
      password: ""


"ContextWeb":
    action: ""
    params: 
      username: ""
      password: ""


"CPX Interactive":
    action: ""
    params: 
      username: ""
      password: ""


"Game Advertising Online":
    action: ""
    params: 
      username: ""
      password: ""


"Google AdSense":
    action: ""
    params: 
      username: ""
      password: ""


"Kitara":
    action: ""
    params: 
      username: ""
      password: ""


"Oridian":
    action: ""
    params: 
      username: ""
      password: ""


"RealTechNetwork":
    action: ""
    params: 
      username: ""
      password: ""


"SixApart":
    action: ""
    params: 
      username: ""
      password: ""


"Test":
    action: ""
    params: 
      username: ""
      password: ""


"Traffic Marketplace Express":
    action: ""
    params: 
      username: ""
      password: ""


"Tribal Fusion":
    action: ""
    params: 
      username: ""
      password: ""


"ValueClick":
    action: ""
    params: 
      username: ""
      password: ""


"VideoEgg":
    action: ""
    params: 
      username: ""
      password: ""


"Widget Bucks":
    action: ""
    params: 
      username: ""
      password: ""

