"Ad.com":
    action: ""
    url: ""    
    params: 
      username: <%= user %>
      password: <%= pass %>


"AdBrite":
    action: "https://www.adbrite.com/mb/commerce/login.php"
    params: 
      username: <%= user %>
      pword:    <%= pass %>

"Advertise Your Game"
    action: "http://advertiseyourgame.com/index.php?view=login"
    params: 
      l_email: <%= user %>
      l_pass: <%= pass %>

"Burst Media":
    action: "https://www.burstmedia.com/PUBLISHERS/login.aspx"
    url: "http://www.burstmedia.com"
    params:
      username: <%= user %>
      password: <%= pass %>

"Casale Media":
    action: "https://casalemedia.com/login"
    url: "http://www.casalemedia.com/"
    params:
      signIn: <%= user %>
      password: <%= pass %>

"ContextWeb":
    action: ""
    url: ""    
    params: 
      username: <%= user %>
      password: <%= pass %>


"CPX Interactive":
    action: "http://reporting.cpxinteractive.com/index.php"
    params: 
      username: <%= user %>
      password: <%= pass %>

"Fox Audience Network (FAN)":
    action: "https://publishers.foxaudiencenetwork.com/j_security_check"
    url: "https://publishers.foxaudiencenetwork.com/pnp/login"   
    params:
      j_username: <%= user %>
      j_password: <%= pass %>


"Game Advertising Online":
    action: ""
    url: ""    
    params: 
      username: <%= user %>
      password: <%= pass %>


"Google AdSense":
    action: "https://www.google.com/accounts/ServiceLoginBoxAuth"
    url: "https://www.google.com/adsense"
    # automated login does not appear to work cleanly
#     params: 
#       username: <%= user %>
#       password: <%= pass %>

"Gorilla Nation":
    action: "https://pubops.gorillanation.com/pubops_account/login"
    params:
      login: <%= user %>
      password: <%= pass %>
      commit: "Log in"


"Kitara":
    action: "http://aristotle.kitaramedia.com/web/"
    params: 
      'signin[username]': <%= user %>
      'signin[password]': <%= pass %>

"Microsoft PubCenter":
    action: "https://beta.pubcenter.microsoft.com/"
    url: "https://beta.pubcenter.microsoft.com/"
# uses JS to do the submits etc, can't do it programatticaly :(
#    params:
#      ctl00_MainContent_txtUserName: <%= user %>
#      ctl00_MainContent_txtPassword: <%= pass %>

"Oridian":
    action: "http://my.adserverplus.com/index.php"
    params: 
      username: <%= user %>
      password: <%= pass %>

"Platform-A":
    action: "https://reports.advertising.com/login?rlp=1&force=0&n=17158986"
    url: "https://reports.advertising.com/login.jsp"
    params: 
      username:         <%= user %>
      password:         <%= pass %>
      Submit:           Login


"Price Grabber":
    action: "https://dnb.doubleclick.net/dnbLogin"
    url: "https://dnb.doubleclick.net/login"
    params: 
      username:         <%= user %>
      password:         <%= pass %>
      'method:login':   'Sign in'

"RealTechNetwork":
    action: "http://publisher.contextualmarketplace.com/checklogin.php"
    params: 
      username: <%= user %>
      password: <%= pass %>
      Submit:   Login

"SixApart":
    action: "https://go.adify.com/Default.aspx"
# dynamic secret strings prohibit automatic logins
#     params: 
#       'ctl00$ctl00$BodyContent$BodyContent$UserName': <%= user %>
#       'ctl00$ctl00$BodyContent$BodyContent$Password': <%= pass %>
#       '__EVENTTARGET': 'ctl00$ctl00$BodyContent$BodyContent$SignInButton'

"Sustain Lane":
    action: "https://go.adify.com/Default.aspx"
# dynamic secret strings prohibit automatic logins
#     params: 
#       'ctl00$ctl00$BodyContent$BodyContent$UserName': <%= user %>
#       'ctl00$ctl00$BodyContent$BodyContent$Password': <%= pass %>
#       '__EVENTTARGET': 'ctl00$ctl00$BodyContent$BodyContent$SignInButton'
      
"Test":
    action: ""
    url: ""    
    params: 
      username: <%= user %>
      password: <%= pass %>


"Traffic Marketplace Express":
    action: "http://adm.trafficmp.com/trafficKing/Login,loginForm.direct"
    url: "http://www.trafficmp.com/login"    
    params: 
      userName:     <%= user %>
      password:     <%= pass %>
      formids:      "userName,password,login"
      Submit:       Submit
      clientType:   1


"Tribal Fusion":
    action: "https://www.tribalfusion.com/adapp/login/checkLogin"
    url: "https://www.tribalfusion.com/adapp/login/expo9"    
    params: 
      username: <%= user %>
      password: <%= pass %>
      expo:     expo9


"ValueClick":
    action: "https://admin.valueclickmedia.com/v4/login.go"
    url: "https://www.valueclickmedia.com/login.shtml"
    params: 
      user_name:    <%= user %>
      password:     <%= pass %>


"VideoEgg":
    action: "https://partners.videoegg.com/p/eap/h/1"
    params: 
      input.login.username: <%= user %>
      input.login.password: <%= pass %>
      form:                 Package.login.login
      doLogin:              true

"Widget Bucks":
    action: "https://www.widgetbucks.com/login.flow"
    params: 
      email:    <%= user %>
      password: <%= pass %>
      action:   call
      formName: login
