development:
  servers:
    - localhost:11211

dev_jos:
  servers:
    - localhost:11211

test:
  servers:
    - localhost:11211

production:
  servers:
    - salt.liftium.com:11211
    - lime.liftium.com:11211

live:
  servers:
    - salt.liftium.com:11211
    - lime.liftium.com:11211
