development:
  servers:
    - localhost:11211

dev_jos:
  servers:
    - localhost:11211

test:
  servers:
    - localhost:11211

production:
  servers:
### disabled memcached2 for now, because the ruby & php libraries are using different
### hashing strategies. See FB 118 for details. -Jos
#    - salt.liftium.com:11211
#    - lime.liftium.com:11211
    - memcached1.liftium.com:11211

live:
  servers:
### disabled memcached2 for now, because the ruby & php libraries are using different
### hashing strategies. See FB 118 for details. -Jos
#    - salt.liftium.com:11211
#    - lime.liftium.com:11211
    - memcached1.liftium.com:11211
